#!/bin/bash

# -- Color Definitions --
export WHITE=0xffffffff
export BLACK=0x00000000

export TRANSPARENT_BG=0x9b1c1823
# export TRANSPARENT_BG=0x0b0b0b0b
export TRANSPARENT_FG=0x0bf141c3f

export LIGHT_GREY=0xff9f9f9f
export DARK_GREY=0xff090909

export GREY_BG=0xff353c3f
export GREY_FG=0xfff141c3f

export YELLOW_BG=0xff8e7e0a
export YELLOW_FG=0xfff7fc17

export ORANGE_BG=0xff99440a
export ORANGE_FG=0xfff97716

export GREEN_BG=0xff008c39
export GREEN_FG=0xff1dfca1

export BLUE_BG=0xff131c84
export BLUE_FG=0xff3746f9

export PURPLE=0xff1c1823
export PURPLE_LIGHT=0xff211d29
export PURPLE_LIGHTEST=0xffaa9bd9

export PURPLE_BG=0xff2b1c84
export PURPLE_FG=0xffeb46f9

export RED_BG=0xff591221
export RED_FG=0xffff2453

# -- Scheme Settings --
export BAR_COLOR=$TRANSPARENT_BG

export ITEM_COLOR_BG=$PURPLE_LIGHT
export ITEM_COLOR_FG=$PURPLE_LIGHTEST

export ACTIVE_ITEM_BG=$PURPLE
export ACTIVE_ITEM_FG=$WHITE

export MEDIA_COLOR_BG=$PURPLE
export MEDIA_COLOR_FG=$PURPLE_FG

export CPU_COLOR_BG=$GREEN_BG
export CPU_COLOR_FG=$GREEN_FG

export MEM_COLOR_BG=$PURPLE_BG
export MEM_COLOR_FG=$PURPLE_FG

export TEMP_COLOR_BG=$ORANGE_BG
export TEMP_COLOR_FG=$ORANGE_FG

export VOLUME_COLOR_BG=$YELLOW_BG
export VOLUME_COLOR_FG=$YELLOW_FG

export BATTERY_COLOR_BG=$RED_BG
export BATTERY_COLOR_FG=$RED_FG

export LANG_COLOR_BG=$BLUE_BG
export LANG_COLOR_FG=$BLUE_FG

export WEATHER_COLOR_BG=$TRANSPARENT_BG
export WEATHER_COLOR_FG=$PURPLE_LIGHTEST

export CALENDAR_COLOR_BG=$TRANSPARENT_BG
export CALENDAR_COLOR_FG=$PURPLE_LIGHTEST
