#!/bin/bash

source "$CONFIG_DIR/colors.sh" # Loads all defined colors

# This is a demo config to show some of the most important commands more easily.
# This is meant to be changed and configured, as it is intentionally kept sparse.
# For a more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

##### Bar Appearance #####
# Configuring the general appearance of the bar, these are only some of the
# options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar height=20 \
                 blur_radius=20 \
                 position=top \
                 sticky=off \
                 padding_left=0 \
                 padding_right=0 \
                 color=$BAR_COLOR

##### Changing Defaults #####
# We now change some default values that are applied to all further items
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

sketchybar --default icon.font="SF Pro:Semibold:12.0" \
                     icon.color=$ITEM_COLOR_FG \
                     label.font="SF Pro:Semibold:12.0" \
                     label.color=$ITEM_COLOR_FG \
                     background.color=$ITEM_COLOR_BG \
                     background.corner_radius=5 \
                     background.height=24 \
                     padding_left=0 \
                     padding_right=1 \
                     label.padding_left=4 \
                     label.padding_right=10 \
		     label.font.color=$WHITE \
                     icon.padding_left=10 \
                     icon.padding_right=4

# -- Left Side Items from Left to Right --
source $ITEM_DIR/spaces.sh
source $ITEM_DIR/front_app.sh


# -- Right Side Items from Right to Left --
source $ITEM_DIR/calendar.sh
source $ITEM_DIR/weather.sh
source $ITEM_DIR/input_lang.sh
source $ITEM_DIR/volume.sh
source $ITEM_DIR/battery.sh
source $ITEM_DIR/cpu.sh
source $ITEM_DIR/media.sh


##### Finalizing Setup #####
# The below command is only needed at the end of the initial configuration to
# force all scripts to run the first time, it should never be run in an item script.

sketchybar --hotload on

sketchybar --update
