#!/bin/bash

# reset XDPH for screenshare
sleep 1
killall xdg-desktop-portal-hyprland
#killall xdg-desktop-portal-gnome
#killall xdg-desktop-portal-kde
#killall xdg-desktop-portal-lxqt
#killall xdg-desktop-portal-wlr
killall xdg-desktop-portal-gtk
killall xdg-desktop-portal
sleep 1
/usr/lib/xdg-desktop-portal-hyprland &
sleep 1
/usr/lib/xdg-desktop-portal &
sleep 1
/usr/lib/xdg-desktop-portal-gtk &

# https://wiki.hyprland.org/FAQ/#some-of-my-apps-take-a-really-long-time-to-open
# https://gist.github.com/PowerBall253/2dea6ddf6974ba4e5d26c3139ffb7580
dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS WAYLAND_DISPLAY XAUTHORITY XDG_CURRENT_DESKTOP=hyprland XDG_SESSION_TYPE=wayland XDG_SESSION_DESKTOP=hyprland &
#dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP & # for XDPH
#dbus-update-activation-environment --systemd --all &                               # for XDPH
#systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &          # for XDPH
